### ISSUE TITLE
Automated NuGet package creation

### ISSUE THREAD

**Issue by rasmus** [eventflow/EventFlow.Firebase#1]
Please setup automated builds for the repo, making it possible for others to contribute as well.

I would prefer if you could add me as owner as well (https://www.nuget.org/profiles/rasmus) as I would really like this to be an success and would like to pass it on if @warren-pieterse and @janfeyen is maintaining the repo.

**Comment by janfeyen** [comment]
@rasmus ok ... we will but we have just gone live with a big project and about to go live with another one.
We are very stressed for time at the moment.
I am more than happy for other people to jump in as well

**Comment by janfeyen** [comment]
@rasmus you are the owner, you created both the EventFlow.Firebase and the EventFlow.MongoDB repo's.
I do not have permissions to add collaborators, the settings tab doesn't show.

**Comment by rasmus** [comment]
@janfeyen I was refering to the NuGet packages on nuget.org. I completely understand that not everyone has the time for open source dev, which is why I'm trying to bring more on board. I don't have time to manage all potential new integrations, but I would like to be able to pass on the maintainer role of e.g. the MongoDB and Firebass packages if you are occupied.

**Comment by janfeyen** [comment]
@rasmus  apolgies ... happens when one's trying to do a million things at once...
added you to both NuGet packages (EventFlow.MongoDB and EventFlow.Firebase)

**Comment by rasmus** [comment]
thanks

**Comment by rasmus** [comment]
Project added https://ci.appveyor.com/project/eventflow/eventflow-firebase
